-- MySQL Script generated by MySQL Workbench
-- Mon Dec 21 22:36:12 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema kviz
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `kviz` ;

-- -----------------------------------------------------
-- Schema kviz
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `kviz` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `kviz` ;

-- -----------------------------------------------------
-- Table `kviz`.`categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kviz`.`categories` ;

CREATE TABLE IF NOT EXISTS `kviz`.`categories` (
  `Cat_id` INT(11) NOT NULL AUTO_INCREMENT,
  `Cat_name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`Cat_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `kviz`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kviz`.`users` ;

CREATE TABLE IF NOT EXISTS `kviz`.`users` (
  `user_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(100) NOT NULL,
  `mobile_no` VARCHAR(12) NOT NULL,
  `paasword` VARCHAR(250) NOT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `fullname` VARCHAR(250) NOT NULL,
  `google_id` VARCHAR(255) NULL DEFAULT NULL,
  `activeToken` VARCHAR(255) NULL DEFAULT NULL,
  `activeExpires` VARCHAR(255) NULL DEFAULT NULL,
  `activestatus` TINYINT(4) NULL DEFAULT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `email` (`email` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `kviz`.`quiz`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kviz`.`quiz` ;

CREATE TABLE IF NOT EXISTS `kviz`.`quiz` (
  `quiz_id` INT(11) NOT NULL,
  `creator_id` BIGINT(20) NOT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `tittle` VARCHAR(70) NOT NULL,
  `description` VARCHAR(250) NOT NULL,
  `overall_timer` INT(11) NULL DEFAULT NULL,
  `quiz_present_date` DATE NULL DEFAULT NULL,
  `quiz_thumbnail` BLOB NULL DEFAULT NULL,
  `quiz_pin` VARCHAR(250) NULL DEFAULT NULL,
  PRIMARY KEY (`quiz_id`),
  UNIQUE INDEX `user_id` (`creator_id` ASC),
  UNIQUE INDEX `creator_id` (`creator_id` ASC),
  CONSTRAINT `FK_quizCreator`
    FOREIGN KEY (`creator_id`)
    REFERENCES `kviz`.`users` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `kviz`.`question`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kviz`.`question` ;

CREATE TABLE IF NOT EXISTS `kviz`.`question` (
  `question_id` INT(11) NOT NULL AUTO_INCREMENT,
  `quiz_id` INT(11) NOT NULL,
  `Cat_id` INT(11) NOT NULL,
  `question_type` ENUM('MCQ', 'Fillup', 'Polling') NOT NULL,
  `question_statement` VARCHAR(250) NOT NULL,
  `serial_no` INT(11) NOT NULL,
  `difficulty` ENUM('Easy', 'Medium', 'Hard') NOT NULL,
  `question_timer` INT(11) NOT NULL,
  `correct_option` VARCHAR(50) NULL DEFAULT NULL,
  `max_points` INT(11) NOT NULL,
  `question_image` LONGBLOB NULL DEFAULT NULL,
  PRIMARY KEY (`question_id`),
  INDEX `FK_quest_quiz` (`quiz_id` ASC),
  INDEX `FK_quest_cat` (`Cat_id` ASC),
  CONSTRAINT `FK_quest_cat`
    FOREIGN KEY (`Cat_id`)
    REFERENCES `kviz`.`categories` (`Cat_id`),
  CONSTRAINT `FK_quest_quiz`
    FOREIGN KEY (`quiz_id`)
    REFERENCES `kviz`.`quiz` (`quiz_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `kviz`.`options`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kviz`.`options` ;

CREATE TABLE IF NOT EXISTS `kviz`.`options` (
  `option_id` INT(11) NOT NULL AUTO_INCREMENT,
  `question_id` INT(11) NOT NULL,
  `option_statement` VARCHAR(50) NOT NULL,
  `serial_no` INT(11) NOT NULL,
  PRIMARY KEY (`option_id`),
  INDEX `FK_options_quest` (`question_id` ASC),
  CONSTRAINT `FK_options_quest`
    FOREIGN KEY (`question_id`)
    REFERENCES `kviz`.`question` (`question_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `kviz`.`tags`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kviz`.`tags` ;

CREATE TABLE IF NOT EXISTS `kviz`.`tags` (
  `tag_id` INT(11) NOT NULL AUTO_INCREMENT,
  `tag_name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`tag_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `kviz`.`question_tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kviz`.`question_tag` ;

CREATE TABLE IF NOT EXISTS `kviz`.`question_tag` (
  `tag_id` INT(11) NULL DEFAULT NULL,
  `question_id` INT(11) NULL DEFAULT NULL,
  INDEX `FK_question_tag` (`question_id` ASC),
  INDEX `FK_question_tag2` (`tag_id` ASC),
  CONSTRAINT `FK_question_tag`
    FOREIGN KEY (`question_id`)
    REFERENCES `kviz`.`question` (`question_id`),
  CONSTRAINT `FK_question_tag2`
    FOREIGN KEY (`tag_id`)
    REFERENCES `kviz`.`tags` (`tag_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `kviz`.`responses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kviz`.`responses` ;

CREATE TABLE IF NOT EXISTS `kviz`.`responses` (
  `response_id` INT(11) NOT NULL AUTO_INCREMENT,
  `participant_id` BIGINT(20) NOT NULL,
  `quiz_id` INT(11) NOT NULL,
  `option_id` INT(11) NOT NULL,
  `question_id` INT(11) NOT NULL,
  `response_statement` VARCHAR(50) NULL DEFAULT NULL,
  `response_time` VARCHAR(30) NULL DEFAULT NULL,
  PRIMARY KEY (`response_id`),
  INDEX `FK_resp_parti` (`participant_id` ASC),
  INDEX `FK_resp_quiz` (`quiz_id` ASC),
  INDEX `FK_resp_question` (`question_id` ASC),
  INDEX `FK_resp_option` (`option_id` ASC),
  CONSTRAINT `FK_resp_option`
    FOREIGN KEY (`option_id`)
    REFERENCES `kviz`.`options` (`option_id`),
  CONSTRAINT `FK_resp_parti`
    FOREIGN KEY (`participant_id`)
    REFERENCES `kviz`.`users` (`user_id`),
  CONSTRAINT `FK_resp_question`
    FOREIGN KEY (`question_id`)
    REFERENCES `kviz`.`question` (`question_id`),
  CONSTRAINT `FK_resp_quiz`
    FOREIGN KEY (`quiz_id`)
    REFERENCES `kviz`.`quiz` (`quiz_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
